In [1]:
from pertussis import *
logger.setLevel(logging.INFO)
%load_ext autoreload
%autoreload 2
# Initial
r_start = 1929
r_end = 2014
step = 1 / N

# Data
data_M, months = cases_monthly()
# data_M = ma.array(data_M)
# data_M[data_M > 150] = 150 #ma.masked
state_0 = collect_state0()

2017-11-02-18-21-52.log
(192,) (3, 192)


# Make Model

## Distributions

In [2]:
dist_om = uniform(3.5,1)
dist_phi = uniform(0, 2 * np.pi)
dist_rho = uniform(1, 99)
dist_f   = uniform(0.00, 0.5)
dist_e   = uniform(0.5,0.5)
dists = [dist_om, dist_phi, dist_rho, dist_f, dist_f, dist_f, dist_e]

## Build MCMC
Init or load

### Load

In [7]:
# Load
del(mcmcs)
vers = 'chains/1031-4-chains'
# vers = ''
print ('./' + vers)
mcmcs = [load_mcmc('./' + vers + 'mcmc_{}.pkl'.format(i)) for i in range(3)]
mcmcs[1]['active'] = False

./chains/1031-4-chains


### Initialize

In [3]:
extra_params = dict (cov = np.diag((0.2, np.pi / 10, 0.2, 5e-6, 5e-6, 5e-6)),
                    datax=data_M,
                    dists=dists,
                    names = ['omega','phi','rho','f1','f2','f3'], 
                    datay = months,
                    active_params = [1,3,4,5],
                    sigma = 50)

In [4]:
# Initialize
np.random.seed(314)
mcmcs = []

# Chains
om, phi, rho, f1, f2, f3, e =  3.9805, 1.45,  50,   0.0008,   0.0004,   0.00007, 1
mcmc0 = init_mcmc('mcmc_0', state_0, r_start, r_end, om, phi, rho, f1, f2, f3,
                 **extra_params)
mcmcs.append(mcmc0)

om, phi, rho, f1, f2, f3, e = 3.9805,   np.pi,  50,   0.0010,   0.00125,   0.00008,   1
mcmc1 = init_mcmc('mcmc_1', state_0, r_start, r_end, om, phi, rho, f1, f2, f3, 
                 **extra_params)
mcmcs.append(mcmc1)

# om, phi, rho, f1, f2, f3, e =  3.9805, 2.8256, 50,  0.0012, 0.0003, 0.0001, 1
# mcmc2 = init_mcmc('mcmc_2', state_0, r_start, r_end, om, phi, rho, f1, f2, f3, 
#                  **extra_params)
# mcmcs.append(mcmc2)

# om, phi, rho, f1, f2, f3, e =  3.9805, np.pi / 2, 50,  0.009, 0.0005, 0.00006, 1
# mcmc3 = init_mcmc('mcmc_3', state_0, r_start, r_end, om, phi, rho, f1, f2, f3, 
#                  **extra_params)
# mcmcs.append(mcmc3)

[ 1.45    0.0008  0.0004  0.0001] (3.9805, 1.45, 50, 0.0008, 0.0004, 7e-05)
[ 3.1416  0.001   0.0013  0.0001] (3.9805, 3.141592653589793, 50, 0.001, 0.00125, 8e-05)


In [6]:
# for mc in mcmcs[0:]:
#     mc['active'] = True 
# all([mc['active'] for mc in mcmcs])

True

### Loop

In [16]:
n=len(mcmcs)
[x for x in zip(n*[np.random.random()],n*[5000],n*['45'])]

[(0.5885419136419221, 5000, '45'), (0.5885419136419221, 5000, '45')]

In [14]:
sample(mcmcs, iterations = 201, recalculate=20, sd_stop_after=5000, scaling_stop_after=5000)

[ 20.  20.  20.  20.  20.  20.  20.  20.  20.  20.   1.]
WTF
finish 1 super


IndexError: tuple index out of range

In [11]:
from functools import partial

In [ ]:
partial()